defaults:
  # Common setup.
  - setup
  # This file.
  - _self_

dataset_args:
  dataset_name: ${data_dir}/shared/datasets/tulu-3-sft-mixture # allenai/tulu-3-sft-mixture
  output_path: ${data_dir}/shared/datasets/tulu-3-sft-mixture-split
  train_split:
    name: train
  eval_split:
    name: validation
    ratio: 0.05
  stratify_by_column: source

seed: 42