defaults:
  # Common setup.
  - setup
  # This file.
  - _self_

dataset_args:
  dataset_name: ${data_dir}/shared/datasets/tulu-3-sft-mixture # or equivalently allenai/tulu-3-sft-mixture
  output_path: ${data_dir}/shared/datasets/tulu-3-sft-mixture-split
  train_split:
    name: train
  eval_split:
    name: validation
    ratio: 0.01 # ratio of the training dataset to be used for validation
  stratify_by_column: source

seed: 42
