# An example config file for an experiment.
# Keep this, it's used as an example to run the code after a user installs the project.

defaults:
  # Common setup.
  - setup
  # This file.
  - _self_
  # Reward model (from the configs/reward_model/ directory).
  - dataset: swissai-olmo2-32b-preference


######################################################################

max_seq_len: 4096
dataset_id: null
dataset_type: train-datasets
swissaiformat_save_path: ${artifacts_dir}/${artifacts_subdir}/datasets/alignment-pipeline-swissaiformat/${dataset_type}/swissaiformat/${dataset_id}
preference_save_path: ${artifacts_dir}/${artifacts_subdir}/datasets/alignment-pipeline-swissaiformat/${dataset_type}/preference-format/${dataset_id}
num_pairs_per_prompt: 3
min_num_ref_rewards: 2 # filter prompts with less than this many reference rewards
seed: 43
