defaults:
  # Common setup.
  - setup
  # SFT configuration
  - trl-sft
  # This file.
  - _self_

plw_args:
  prompt_loss_weight: 0.1

training_args:
  dataloader_drop_last: true
  dataset_kwargs:
    skip_prepare_dataset: true # For PLW: Requires custom dataset preprocessing
  remove_unused_columns: false # For PLW: makes custom fields (like 'completion_mask') available inside compute_loss function
