defaults:
  - setup
  - _self_
  # Model (from the configs/model/ directory).
  - model: tulu-3-8b-sft
  # Dataset (from the configs/dataset/ directory).
  - dataset: tulu-3-8b-preference-mixture
  # Optional preset for training parameters.
  - optional preset: none

######################################################################

dataset_args:
  debug_oom: false # Reorder the dataset with largest batch first to test OOM
  debug_subsample:
    train: 0
    eval: 0

script_args:
  dataset_name: ${dataset_args.dataset_name}
  dataset_train_split: ${dataset_args.train_split.name}
  dataset_test_split: ${dataset_args.eval_split.name}

trainer: dpo
training_args:
  bf16: true
  max_prompt_length: 2048
  max_completion_length: 2048
  max_grad_norm: 1000 # clipping (1_000 represents no clipping)
  learning_rate: 5e-07
  lr_scheduler_type: linear
  warmup_ratio: 0.1
  weight_decay: 0.0
  beta: 5
  label_smoothing: 0.0
  num_train_epochs: 1
  optim: adamw_torch_fused
  dataloader_drop_last: true
  remove_unused_columns: false # required for custom data collator
  per_device_train_batch_size: 2 # note, this is set up for 4 GPUs
  gradient_accumulation_steps: 4 # effective batch size 128 with 4 nodes
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false # https://pytorch.org/docs/stable/checkpoint.html, https://github.com/huggingface/trl/issues/1348
  average_tokens_across_devices: true # More accurate loss.
  logging_first_step: true
  logging_steps: 25
  per_device_eval_batch_size: 2
  eval_strategy: "no" # use "no" for no evaluation
  eval_steps: 50
  eval_on_start: false
  save_strategy: epoch
  # save_steps: 50 # only required if save_strategy=steps
  report_to: wandb
  seed: ${seed}
  dataset_num_proc: 8
  dataloader_num_workers: 8

seed: 42

resuming:
  resume: false
  exclude_keys:
    - run_dir
    - data_dir
    - outputs_dir
    - resuming_dir
    - wandb
    - resuming.exclude_keys
    - training_args.logging_dir
