# An example config file for an experiment.
# Keep this, it's used as an example to run the code after a user installs the project.

defaults:
  # Common setup.
  - setup
  # This file.
  - _self_
  # Model (from the configs/model/ directory).
  - model: mistralai-mistral-7b-instruct
  # Dataset (from the configs/dataset/ directory).
  - dataset: magpieair
  # Optional preset for training parameters.
  - optional preset: none

######################################################################

# model_args from the model config file
# reward_model_args from the reward model config file
# dataset args from the dataset config file

dataset_args:
  debug_oom: false # Reorder the dataset with largest batch first to test OOM
  debug_subsample:
    train: 0
    eval: 0
script_args:
  dataset_name: ${dataset_args.dataset_name}
  dataset_train_split: ${dataset_args.train_split.name}
  dataset_test_split: ${dataset_args.eval_split.name}
training_args:
  bf16: true
  max_seq_length: 2048
  learning_rate: 2.0e-5
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  num_train_epochs: 1
  packing: false
  dataloader_drop_last: true
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 16
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false # https://pytorch.org/docs/stable/checkpoint.html, https://github.com/huggingface/trl/issues/1348
  average_tokens_across_devices: true # More accurate loss.
  logging_first_step: true
  logging_steps: 5
  eval_strategy: steps
  eval_steps: 100
  eval_on_start: true
  per_device_eval_batch_size: 2
  save_strategy: steps
  save_steps: 100
  report_to: wandb
  seed: ${seed}
  dataloader_num_workers: 8

seed: 42

resuming:
  resume: false
  exclude_keys:
    - run_dir
    - data_dir
    - outputs_dir
    - resuming_dir
    - wandb
    - resuming.exclude_keys
    - training_args.logging_dir
