# @package _global_

model_args:
  torch_dtype: bfloat16
  model_name_or_path: /capstor/store/cscs/swissai/a06/hf_checkpoints/Apertus3-70B_iter_90000
  attn_implementation: flash_attention_2
  trust_remote_code: true
  use_peft: false

tokenizer_args:
  tokenizer_name_or_path: /capstor/store/cscs/swissai/a06/hf_checkpoints/Apertus3-70B_iter_90000
  chat_template_name: tulu
  trust_remote_code: true
  padding_side: right
  add_bos: false
  model_pad_token_id: 10  # <pad>
  model_eos_token_id: null # keep default. (2: </s>)
