# @package _global_

dataset_name: Apertus-8B-aligned_0.1_0.7_correctness_no_refuse_sft_data

dataset_args:
  dataset_name: /capstor/store/cscs/swissai/infra01/users/bmessmer/Apertus-8B-aligned_0.1_0.7_correctness_no_refuse_sft_data
  train_split: # Only required for DatasetDict objects
    name: null
  eval_split:
    name: null

training_args:
  eval_strategy: "no"
  eval_steps: null