# @package _global_

dataset_name: Apertus-8B-aligned_0.1_0.7_correctness_no_refuse_sft_data

dataset_args:
  dataset_name: /iopsstor/scratch/cscs/bmessmer/SFT4Honesty/Apertus-8B-aligned_0.1_0.7_correctness_no_refuse_sft_data/ # /iopsstor/scratch/cscs/bmessmer/SFT4Honesty/german-sft4Honesty-2thresholds
  train_split: # Only required for DatasetDict objects
    name: null
  eval_split:
    name: null

training_args:
  eval_strategy: "no"
  eval_steps: null