# @package _global_

dataset_name: allenai/tulu-3-sft-mixture

dataset_args:
  dataset_name: ${data_dir}/shared/datasets/tulu-3-sft-mixture
  # TODO
  train_split:
    name: train


training_args:
  eval_strategy: "no"
  eval_steps: 160
  save_steps: 160