# @package _global_

dataset_name: tulu3-sft-mixture-1-decontaminated

dataset_args:
  dataset_name: /capstor/store/cscs/swissai/infra01/posttrain_data/06_sft_mixtures_newformat/tulu3-sft-mixture-1-decontaminated
  train_split: # Only required for DatasetDict objects
    name: null
  eval_split:
    name: null

training_args:
  eval_strategy: "no"
  eval_steps: null
